export { Home } from "./Home";
export { FullPost } from "./FullPost";
export { AddPost } from "./AddPost";
export { Registration } from "./Registration";
export { Login } from "./Login";
export { Counter } from "./smallProjects/Counter/Counter";
export { Quiz } from "./smallProjects/Quiz/Quiz";
export { Photos } from "./smallProjects/Photos/Photos";
export { ListUsers } from "./smallProjects/ListUsers/ListUsers";
export { Converter} from "./smallProjects/Converter/Converter";